version: "3"
services:
 backend:
    image:  {{cookiecutter.project_name}}_dev
    container_name: {{cookiecutter.project_name}}_dev
    build: 
      context: .
      dockerfile: ./config/docker/Dockerfile
    env_file:
      - .env
    volumes:
      - '.:/app'
    tty: true
    ports:
      - ${BACKEND_PORT:-6543}:${BACKEND_PORT:-6543}
      - 10001:10001
    entrypoint:
      - python
      - -m
      - debugpy
      - --listen
      - 0.0.0.0:10001
      - /usr/local/bin/gunicorn
      - --paster
      - ./config/development.ini
      - -b
      - 0.0.0.0:${BACKEND_PORT:-6543}
      - --reload